const sites = [
  {
    name: "BOOK GENRES - FINAL PROJECT",
    type: "project",
    url: "https://page--turner.herokuapp.com/",
    site: "Heroku",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-final_project",
    image: "/images/books.png",
    tech: [
      "JavaScript",
      "React",
      "Heroku",
      "MongoDB",
      "NodeJs",
      "Express",
      "Axios",
      "RESTful API",
      "CORS",
      "JWT",
      "BCrypt",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "FBI API - MID PROJECT",
    type: "project",
    url: "https://fbi-crime-api.netlify.app",
    site: "Netlify",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-fbi_api",
    image: "/images/fbi.jpg",
    tech: [
      "JavaScript",
      "Netlify",
      "React",
      "Axios",
      "RESTful API",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "MINECRAFT",
    type: "exercise",
    url: "https://happy-wing-768fcc.netlify.app",
    site: "Netlify",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-minecraft",
    image: "/images/minecraft.jpg",
    tech: ["JavaScript", "Netlify", "Git", "GitHub", "HTML", "CSS"],
  },
  {
    name: "AMAZON PRODUCT PAGE",
    type: "exercise",
    url: "https://admiring-keller-5dc5d7.netlify.app",
    site: "Netlify",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-amazon_page",
    image: "/images/amazon-item.jpg",
    tech: ["JavaScript", "Netlify", "Git", "GitHub", "HTML", "CSS"],
  },
  {
    name: "HTML & CSS PROFILE",
    type: "exercise",
    url: "https://priceless-liskov-27ebf6.netlify.app",
    site: "Netlify",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-personal_profile",
    image: "/images/personal-profile.jpg",
    tech: ["HTML", "CSS", "Git", "GitHub", "Netlify"],
  },
  {
    name: "APPLE HOME PAGE",
    type: "exercise",
    url: "https://peaceful-joliot-09629c.netlify.app/#",
    site: "Netlify",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-apple_main",
    image: "/images/apple-front-page.jpg",
    tech: ["HTML", "CSS", "Git", "GitHub", "Netlify"],
  },
  {
    name: "CAT CRUD",
    type: "exercise",
    url: "https://determined-joliot-b24be6.netlify.app/",
    site: "Netlify",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-shoe_app",
    image: "/images/cat-crud.jpg",
    tech: [
      "JavaScript",
      "Netlify",
      "React",
      "Axios",
      "RESTful API",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "COVID BY COUNTRY",
    type: "exercise",
    url: "https://reverent-hamilton-257a3a.netlify.app/",
    site: "Netlify",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-covid_by_country",
    image: "/images/covid.jpg",
    tech: [
      "JavaScript",
      "Netlify",
      "ChartJs",
      "Axios",
      "RESTful API",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "DICE GAME",
    type: "exercise",
    url: "https://affectionate-fermat-047afc.netlify.app/",
    site: "Netlify",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-dice_game",
    image: "/images/dice.png",
    tech: ["JavaScript", "Netlify", "React", "Git", "GitHub", "HTML", "CSS"],
  },
  {
    name: "eCOMMERCE SITE",
    type: "exercise",
    url: "https://suspicious-boyd-25985b.netlify.app/",
    site: "Netlify",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-ecommerce_site",
    image: "/images/e-comm.png",
    tech: [
      "JavaScript",
      "Netlify",
      "React",
      "Axios",
      "RESTful API",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "LIKE / UNLIKE",
    type: "exercise",
    url: "https://gifted-volhard-c380ea.netlify.app/",
    site: "Netlify",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-match_finding",
    image: "/images/like-unlike.png",
    tech: [
      "JavaScript",
      "Netlify",
      "React",
      "Axios",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "MEMORY FLASH CARDS",
    type: "exercise",
    url: "https://adoring-volhard-05baca.netlify.app/",
    site: "Netlify",
    repo: "https://github.com/AltaraceO/fullstack_bootcamp-flash_cards",
    image: "/images/flash-cards.png",
    tech: [
      "JavaScript",
      "Netlify",
      "React",
      "Axios",
      "RESTful API",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
];

export default sites;
