const sites = [
  {
    name: "Books",
    url: "https://page--turner.herokuapp.com/",
    image: "/images/books.png",
    tech: [
      "JavaScript",
      "React",
      "Heroku",
      "MongoDB",
      "NodeJs",
      "Express",
      "Axios",
      "RESTful API",
      "CORS",
      "JWT",
      "BCrypt",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "FBI API",
    url: "https://fbi-crime-api.netlify.app",
    image: "/images/fbi.jpg",
    tech: [
      "JavaScript",
      "Netlify",
      "React",
      "Axios",
      "RESTful API",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "Minecraft",
    url: "https://happy-wing-768fcc.netlify.app",
    image: "/images/minecraft.jpg",
    tech: ["JavaScript", "Netlify", "Git", "GitHub", "HTML", "CSS"],
  },
  {
    name: "Amazon Product Page",
    url: "https://admiring-keller-5dc5d7.netlify.app",
    image: "/images/amazon-item.jpg",
    tech: ["JavaScript", "Netlify", "Git", "GitHub", "HTML", "CSS"],
  },
  {
    name: "HTML & CSS Profile",
    url: "https://priceless-liskov-27ebf6.netlify.app",
    image: "/images/personal-profile.jpg",
    tech: ["HTML", "CSS", "Git", "GitHub", "Netlify"],
  },
  {
    name: "Apple Home Page",
    url: "https://peaceful-joliot-09629c.netlify.app/#",
    image: "/images/apple-front-page.jpg",
    tech: ["HTML", "CSS", "Git", "GitHub", "Netlify"],
  },
  {
    name: "Cat CRUD",
    url: "https://determined-joliot-b24be6.netlify.app/",
    image: "/images/cat-crud.jpg",
    tech: [
      "JavaScript",
      "Netlify",
      "React",
      "Axios",
      "RESTful API",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "Covid by Country",
    url: "https://reverent-hamilton-257a3a.netlify.app/",
    image: "/images/covid.jpg",
    tech: [
      "JavaScript",
      "Netlify",
      "ChartJs",
      "Axios",
      "RESTful API",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "Dice Game",
    url: "https://affectionate-fermat-047afc.netlify.app/",
    image: "/images/dice.png",
  },
  {
    name: "eCommerce Site",
    url: "https://suspicious-boyd-25985b.netlify.app/",
    image: "/images/e-comm.png",
    tech: [
      "JavaScript",
      "Netlify",
      "React",
      "Axios",
      "RESTful API",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "Like / Unlike",
    url: "https://gifted-volhard-c380ea.netlify.app/",
    image: "/images/like-unlike.png",
    tech: [
      "JavaScript",
      "Netlify",
      "React",
      "Axios",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
  {
    name: "Memory Flash Cards",
    url: "https://adoring-volhard-05baca.netlify.app/",
    image: "/images/flash-cards.png",
    tech: [
      "JavaScript",
      "Netlify",
      "React",
      "Axios",
      "RESTful API",
      "CORS",
      "CRUD",
      "Git",
      "GitHub",
      "HTML",
      "CSS",
    ],
  },
];

export default sites;
